### ISSUE TITLE
Magento 2.1.5 error when trying to flush cache and setup upgrade

### ISSUE THREAD

**Issue by altheaziyun** [colinmollenhour/credis#117]
I get error below when trying to flush cache and running magento 2 setup upgrade command in Magento 2.1.5, credis version 1.6

`Notice: fwrite(): send of 8192 bytes failed with errno=32 Broken pipe in /var/www/magento2-release/release/vendor/colinmollenhour/credis/Client.php on line 1134`

**Comment by rogan-son** [comment]
It worked on 29 Mar 2019, but suddenly not working from 1 Apr 2019.

**Comment by colinmollenhour** [comment]
Based on the line number not matching that is an older version of the code and I have no control over what version is released with Magento code.. Not that the new version would fix your issue, because it seems to me something else is wrong with your redis instance. This library is a wrapper around phpredis or standard PHP streams so "fwrite()...Broken pipe" indicates a connection issue.

**Comment by rogan-son** [comment]
@colinmollenhour Even though I'd upgraded Ubuntu 14.04 to 16.04 and kernel image to latest version, I had encountered same error @altheaziyun posted.

Since our system can't connet and use redis cache, I'd commented out Cm_Cache_Backend_Redis in env.php for a workaround.

Do you have any idea to sort out this problem?

**Comment by colinmollenhour** [comment]
Just the basic troubleshooting for basic connection issues. Confirm it works using the most basic tool and work from there. E.g. you should be able to connect from the app server using the same settings with `redis-cli`. However, this is not the place for support of such issues, it is only for bug reporting and pull requests.
