### ISSUE TITLE
Connection reset by peer in vendor/colinmollenhour/credis/Client.php

### ISSUE THREAD

**Issue by ilyasmuyiwa** [colinmollenhour/credis#120]
Hi @colinmollenhour, Please I just need a clue on what could cause this error.
`Notice: Redis::exec(): send of 8192 bytes failed with errno=104 Connection reset by peer in vendor/colinmollenhour/credis/Client.php`
This exception always come up just once in a while. When we clear cache, it starts working again. Please, what could cause this issue? Any clue to solve it?

**Comment by colinmollenhour** [comment]
"Connection reset by peer" seems to indicate Redis closed the connection so some sort of limit is being reached somewhere. Unfortunately this isn't the appropriate place to troubleshoot specific production issues, just bug reports. All I can say is make sure your redis instance has enough memory, sane limits etc. I don't think the issue is specific to this library, though.
