### ISSUE TITLE
Uncaught RedisException: read error on connection

### ISSUE THREAD

**Issue by mowny** [colinmollenhour/credis#143]
Over the last few days, I keep getting this more and more often from the magento connector scripts run by cron:
PHP Fatal error:  Uncaught RedisException: read error on connection in /var/www/vhosts/server/httpdocs/magento2/wordpress/shop/vendor/colinmollenhour/credis/Client.php:1130
This is the only common part, after that the stack trace proceeds with e.g. Redis->select(1) or Redis->hGet('zc:k:..', 'd')

Redis 3.2.6 is configured as unix-socket only. I thought the timeouts and such should only happen via tcp?
I'm starting to think something is very, very wrong with the server. Any suggestions where to start looking would be much appreciated.

**Comment by Xon** [comment]
This sort of thing can happen if redis stalls due to kernel stuns when `fork` is called for implementing persistence (either dump or the apend logging). Try adjusting the auto-save interval in redis to occur much less often or switch from the save dump to the append logging.

**Comment by mowny** [comment]
But then, if it was redis' background saving worker, the log would line up with the errors, wouldn't it? I have
```
1071:M 28 Oct 13:43:34.031 * 10 changes in 300 seconds. Saving...
1071:M 28 Oct 13:43:34.118 * Background saving started by pid 29035
29035:C 28 Oct 13:44:28.880 * DB saved on disk
29035:C 28 Oct 13:44:28.937 * RDB: 11 MB of memory used by copy-on-write
1071:M 28 Oct 13:44:29.070 * Background saving terminated with success
1071:M 28 Oct 13:49:30.013 * 10 changes in 300 seconds. Saving...
1071:M 28 Oct 13:49:30.100 * Background saving started by pid 29158
29158:C 28 Oct 13:50:21.795 * DB saved on disk
29158:C 28 Oct 13:50:21.855 * RDB: 11 MB of memory used by copy-on-write
1071:M 28 Oct 13:50:21.948 * Background saving terminated with success
```
and the cronjob that failed ran at 13:45:00 (scheduled at */15). Other failures don't match either.

Must be something else then, I guess. Unfortunately so far I couldn't find anything else in the logs nor in iostat or iotop.

**Comment by mangust404** [comment]
Have you figured it out?

Probably I have the similar error.
I have a setup from 3 physical server where 3 KVM Redis nodes with Sentinel runs on each server and the "read error on connection" is rising only on one of them. Very annoying thing.

**Comment by mowny** [comment]
No.
I have since separated sessions and page cache into separate redis instances and set the dump interval for the page cache redis to 1 day as page cache does not really need to be persistent. The session dumps are below 200KB, so that shouldn't disturb anything.

After the change, I saw no error for a few days, but they started to show up again. Uncorrelated with that daily dump.
So I suspect this is internal memory fragmentation, and redis needs to be restarted every week or so.

**Comment by mangust404** [comment]
Thank you for reply. It more seems like physical problem (CPU or RAM) in our cases rather than some misconfiguration or software bug.
I have almost identical servers but the problem occurs only with one of them.

**Comment by mangust404** [comment]
Nope. Everything is ok with the hardware.

Just little more investigation, debugging and logging on production servers clarified the problem about my "read error on connection" exceptions.

At first, on Redis server start there was several warnings:

`WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.`

and 

`WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.`

So I made
`echo never > /sys/kernel/mm/transparent_hugepage/enabled
sysctl -w net.core.somaxconn=65535`
also you need to put it into your /etc/rc.local and/or /etc/sysctl.conf

And just to decrease disk writes I've increased my "save" values for redis to:
`save 900 100
save 300 1000
save 60 100000`

The problem seems to occur at random because of the increasing amount of crawler bots rushing to my production server. That's why we didn't see it before. But under heavy load Redis hit one of those limits.

I hope that will help to someone.

**Comment by mowny** [comment]
Found something more:
`redis-cli -s /var/run/redis/redis.sock monitor` stops outputting anything after a while, so this seems to be an issue within redis itself.

**Comment by mangust404** [comment]
It seems that your current Redis version has bug which was fixed a long ago and forgotten.
When we moved to 6.0.9 everything goes nice and smooth since then (we had 3.0.7 with the same issue).
