### ISSUE TITLE
read error on connection to REDIS:6379

### ISSUE THREAD

**Issue by Thomsath** [colinmollenhour/credis#169]
**Magento version** : 2.3.7-p2
**Redis version** : 5.0.7
### Issue in exception.log 
`main.CRITICAL: read error on connection to REDIS:6379 {"exception":"[object] (CredisException(code: 2): read error on connection to REDIS:6379 at vendor/colinmollenhour/credis/Client.php:1186, RedisException(code: 0): read error on connection to REDIS:6379 at vendor/colinmollenhour/credis/Client.php:1168)"}`
and 
`main.CRITICAL: Connection to Redis REDIS:6379 failed after 2 failures.Last Error : (1) Connection refused {"exception":"[object] (CredisException(code: 0): Connection to Redis REDIS:6379 failed after 2 failures.Last Error : (1) Connection refused at vendor/colinmollenhour/credis/Client.php:493)"}`
We're facing this issue a lot of time on our server. Note that we have a back office server and a redis server. 
### What we tried : 
**1 -** Check redis response time by `redis-cli --latency`. Output was : `min: 0, max: 2, avg: 0.13 (2400 samples)`. Seems good. 

**2 -** Check redis timeout on **env.php**, value is 2.5.

**3 -** Trying to call redis server with PHP CLI command from back office server : 
`php -r '$rds = new Redis();
try {
    $ret = $rds->pconnect("REDIS", 6379);
    if ($ret == false) {
        echo "Connect return false";
        exit;
    }
    $rds->setOption(3, 2.5);
    var_dump('output');
} catch (Exception $e) {
    var_dump ($e);
}'`
It returns the output, without error. 

**4 -** What we've in our redis logs : `WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect`
`WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled`
I note that on older issues, some people run code to avoid these two warnings. Can these warnings be blocking ?

Any idea ?

Thanks.

**Comment by colinmollenhour** [comment]
Hi Thomas, unfortunately I have no idea.. I don't believe this is a common issue so it would make me think there is something about your particular environment..
Have you tried toggling the persistent connection feature?

**Comment by Thomsath** [comment]
Hi, are persistent connections available for php fpm ?

**Comment by colinmollenhour** [comment]
I think so? But if you didn't have it disabled then enabling probably wouldn't fix anything... If this is a very high-traffic site you may just need to scale out using replication and load balancing.

**Comment by Thomsath** [comment]
What is the better way to test if the server is well proportioned ?

**Comment by colinmollenhour** [comment]
Good question.. Redis is mostly a single-threaded application (there are some threads dedicated to I/O and others) so one thing to watch for is the CPU usage at the level of a single core. That is, a 16-core CPU running just Redis will never hit 100% usage, you could be CPU bound and not know it. However, I don't know if that would explain the "read error on connection" error specifically. According to [this comment](https://github.com/phpredis/phpredis/issues/1543#issuecomment-481068702) the error is caused by timeouts (then why not make the error message say that it timed out?!) so could it be correlated to a specific thing like clearing a cache tag with lots of keys or similar?

Apparently they added a `SLOWLOG` feature at some point so it seems that would be worth looking at.

**Comment by Xon** [comment]
Do you have RDB dumping enabled? Try using AOF instead and relaxing the sync requirements to every second instead of every write.

The background save process creates a fork of the entire process which causes a kernel-driven stun to the entire process as it copies page entries. For caching with redis you want it to touch the disk as little as possible.

**Comment by Thomsath** [comment]
I tried to enable appendonly to 'yes', but this error appends :
`MISCONF Errors writing to the AOF file: No space left on device {"exception":"[object] (CredisException(code: 0): MISCONF Errors writing to the AOF file: No space left on device`
Is it about the hard drive disk ?

**Comment by colinmollenhour** [comment]
The advantage is only if you disable full dumps (`config set save ""` in console to change it temporarily). Honestly for a cache you could run it with no persistence at all and probably be fine, just knowing that restarting Redis will be the same effectively as completely wiping the cache.

**Comment by Thomsath** [comment]
In our case, "save" is already to "" value.
