### ISSUE TITLE
Cluster MGET hash key support

### ISSUE THREAD

**Issue by jozsika** [colinmollenhour/credis#54]
Hi,

When trying to read from a cluster using the MGET command, the \Credis_Cluster::hash($key) method - which md5's the key expects a string, but in case of MGET it receives an array of keys - fails with an E_WARNING.
`md5() expects parameter 1 to be string, array given on line 238 in vendor/colinmollenhour/credis/Cluster.php` 
We use the php-redis client.

Please add an is_array($key) check and then compact the key to a string.

Regards,
L

**Comment by colinmollenhour** [comment]
I don't think compacting the key to a string will work since when using mget it is possible that some of the keys requested are on one node while others are on another node so the only way to get the expected result would be to do potentially multiple mget requests and aggregate them. If you want to implement this I'd be happy to accept a PR, but otherwise I'd say mget is just not currently supported with Credis_Cluster.

A simple solution would be to hash the first key, but this would only work with the assumption that all keys are known to be on the same node which isn't likely.

FYI, even the official [Redis Cluster spec](http://redis.io/topics/cluster-spec) doesn't support mget:

> Redis Cluster implements all the single key commands available in the non-distributed version of Redis.
