### ISSUE TITLE
Connection Retries: Exponential Backoff

### ISSUE THREAD

**Issue by daneren2005** [colinmollenhour/credis#67]
It would be nice to be able to do exponential backoff on the automatic connection retries.  In my experience if it fails the first time, redoing it immediately will usually fail as well.  If you add a small delay (ie: 200ms) it has a much higher chance of success.

Example:

```
$this->connectFailures++;
if ($this->connectFailures <= $this->maxConnectRetries) {
    $timeout = $this->connectionBackoff;
    for($i = 1; $i < $this->connectFailures; $i++) {
        $timeout = $timeout * 2;
    }
    usleep($timeout);
    return $this->connect();
}
```

1st Retry: 100ms
2nd Retry: 200ms
3d Retry: 400ms
etc...

**Comment by colinmollenhour** [comment]
I'm leaning towards the opinion that this is not something that should be default behavior. In some cases it might be better to return an error immediately rather than delay the inevitable (e.g. to prevent too many php processes from using memory). In the case of a single machine or LAN then if it takes 100ms to connect to your Redis server then you have a serious issue and piling up processes in reconnect loops isn't going to help. If there is a case where you need a more robust connection then this logic can be implemented outside of the library with the same effectiveness.
