### ISSUE TITLE
Persistent connections broken with PHP 7.0.18

### ISSUE THREAD

**Issue by tinuzz** [colinmollenhour/credis#79]
When using persistent connections, a uniqe persistence identifier is added to the remote socket specified that is fed to stream_socket_client():

[https://github.com/colinmollenhour/credis/blob/958e188b4c00886ba5f1d98ba5955cea01682a85/Client.php#L430](https://github.com/colinmollenhour/credis/blob/958e188b4c00886ba5f1d98ba5955cea01682a85/Client.php#L430)

In PHP 7.0.18, that breaks, due to this commit:

https://github.com/php/php-src/commit/bab0b99f376dac9170ac81382a5ed526938d595a

Any 'garbage' after the port specification now results in a 'Failed to parse address' error.

I'm not sure how to handle this, I think it's just FYI so you know what may be coming ;-)

I'm also not sure if adding something to the end of the socket specified is actually supported in PHP; I know it used to work, but it is undocumented.

Best regards,
Martijn.

**Comment by Xon** [comment]
Previously the Sentinel.php worked with "127.0.0.1:26379", but as of php 7.1.4, this is broken. The recommended "tcp://127.0.0.1:26379" will work.

Bit annoying in this "looks" like it should work, and previously did. I think it is related to the changes to address this security report; https://bugs.php.net/bug.php?id=74216 Where the inline port number is being ignored.

There is some custom URL parsing which might be passing in an explicit port of 0 rather than null to signal to use the port from the URL.

**Comment by colinmollenhour** [comment]
Looks like this PHP regression will remain..
